# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cjLiteSubWinVinP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import funforhelp as ffp
import functionSA as fsa

class Ui_VinP(object):

    def __init__(self, filename):
        self.filename = filename
        self.Pgas = 0.0
        self.Pliq = 0.0
        self.T = 0.0

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1089, 807)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setFont(font)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setFont(font)
        self.label_5.setObjectName('label_5')
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setFont(font)
        self.label_6.setObjectName('label_6')
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textBrowser")
        self.textEdit.setFont(font)
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        Form.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_3.clicked.connect(Form.close)

        self.pushButton.clicked.connect(self.getData)
        self.pushButton_2.clicked.connect(self.saveData)
        self.lineEdit.textChanged[str].connect(self.changePgas)
        self.lineEdit_2.textChanged[str].connect(self.changePliq)
        self.lineEdit_3.textChanged[str].connect(self.changeT)

        #print(self.filename)

    def changePgas(self, Pnew):

        if Pnew == '':

            self.Pgas = 0.0

        else:

            self.Pgas = np.float(Pnew)

        print(self.Pgas)

    def changePliq(self, Pnew):

        if Pnew == '':

            self.Pliq = 0.0

        else:

            self.Pliq = np.float(Pnew)

        print(self.Pliq)

    def changeT(self, Tnew):

        if Tnew == '':

            self.T = 0.0

        else:

            self.T = np.float(Tnew)

        print(self.T)

    def getData(self):

        Const = fsa.Constant(self.filename)

        self.Out = ffp.DataForVinP(Const, self.Pgas * 1.0e5, self.Pliq * 1.0e5, self.T)

        self.textEdit.setText(self.Out)

    def saveData(self):

        out = open(str(np.round(self.Pgas, 2)) + 'bar' + str(np.round(self.Pliq, 2)) + 'bar' + str(
            np.round(self.T, 2)) + 'K.txt', 'w')

        out.write(self.Out)

        out.close()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Condition in point"))
        self.label.setText(_translate("Form", "P GAS ="))
        self.label_4.setText(_translate('Form', 'BAR'))
        self.label_2.setText(_translate("Form", "P LIQUID ="))
        self.label_5.setText(_translate('Form', 'BAR'))
        self.label_3.setText(_translate("Form", "T ="))
        self.label_6.setText(_translate('Form', 'K'))
        self.pushButton_2.setText(_translate("Form", "Save"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.pushButton_3.setText(_translate("Form", "Exit"))
